- name: Start a server running on a remote node
  hosts: all

  tasks:
    - name: Kill running servers
      shell: pkill java  # nuke all the java processes
      ignore_errors: yes

    - name: Copy over the servers.txt file
      copy: 
        src: ../deploy/servers.txt
        dest: ~/

    - name: Launch server
      shell: nohup java -jar -Xmx64m server.jar {{ inventory_hostname }}:{{ port_num }} >/dev/null 2>&1 &

    - name: Check that process is now running
      shell: pgrep java  # fails if there is no java process